// AUTO-GENERATED by scripts/import-styles.js — DO NOT EDIT BY HAND
module.exports = [
  {
    "id": "real-1",
    "title": "裸透粉·纯色",
    "coverUrl": "http://p0.meituan.net/pilotimages/87797733466cfd525625a5947767e2ff1794125.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/8491d190aeb8f44e32f6b278535bf2b41075477.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/87797733466cfd525625a5947767e2ff1794125.png",
      "http://p0.meituan.net/pilotimages/8491d190aeb8f44e32f6b278535bf2b41075477.png"
    ],
    "color": "裸透粉",
    "design": "纯色",
    "styleLabel": "温柔",
    "shapeLabel": "杏仁",
    "styleTags": [
      "gentle"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "almond"
    ],
    "heat": 1960,
    "rankWeight": 1.96,
    "isActive": true,
    "merchantId": null,
    "brief": "裸透粉·纯色·温柔",
    "stylePrompt": "solid 裸透粉 color, 温柔 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-2",
    "title": "奶茶色·法式",
    "coverUrl": "http://p0.meituan.net/pilotimages/162afb52255bd908ba3ec418fd61824a2254875.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/493fc5818746fe45d9be82763034edbe1246574.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/162afb52255bd908ba3ec418fd61824a2254875.png",
      "http://p1.meituan.net/pilotimages/493fc5818746fe45d9be82763034edbe1246574.png"
    ],
    "color": "奶茶色",
    "design": "法式",
    "styleLabel": "法式",
    "shapeLabel": "方形",
    "styleTags": [
      "french"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "square"
    ],
    "heat": 1920,
    "rankWeight": 1.92,
    "isActive": true,
    "merchantId": null,
    "brief": "奶茶色·法式·法式",
    "stylePrompt": "solid 奶茶色 color, 法式 nail art pattern, 法式 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-3",
    "title": "酒红·渐变",
    "coverUrl": "http://p1.meituan.net/pilotimages/7bb5bc0c2c741f9f0aa63787a601d7ad2604877.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/667658abb96c7547791d48360a8e95b61155924.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/7bb5bc0c2c741f9f0aa63787a601d7ad2604877.png",
      "http://p0.meituan.net/pilotimages/667658abb96c7547791d48360a8e95b61155924.png"
    ],
    "color": "酒红",
    "design": "渐变",
    "styleLabel": "极简",
    "shapeLabel": "圆形",
    "styleTags": [
      "minimal"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1880,
    "rankWeight": 1.88,
    "isActive": true,
    "merchantId": null,
    "brief": "酒红·渐变·极简",
    "stylePrompt": "solid 酒红 color, 渐变 nail art pattern, 极简 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-4",
    "title": "樱花粉·猫眼",
    "coverUrl": "http://p0.meituan.net/pilotimages/fc8fe60e78341d77a5070fc2f8e520072098070.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/f8539918c55c5c1e4a45ee3996df65f7167977.jpg",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/fc8fe60e78341d77a5070fc2f8e520072098070.png",
      "http://p1.meituan.net/pilotimages/f8539918c55c5c1e4a45ee3996df65f7167977.jpg"
    ],
    "color": "樱花粉",
    "design": "猫眼",
    "styleLabel": "奶油",
    "shapeLabel": "梯形",
    "styleTags": [
      "cream"
    ],
    "materialTags": [
      "cat-eye"
    ],
    "shapeTags": [
      "trapezoid"
    ],
    "heat": 1840,
    "rankWeight": 1.8399999999999999,
    "isActive": true,
    "merchantId": null,
    "brief": "樱花粉·猫眼·奶油",
    "stylePrompt": "solid 樱花粉 color, 猫眼 nail art pattern, 奶油 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-5",
    "title": "雾霾蓝·亮片",
    "coverUrl": "http://p1.meituan.net/pilotimages/3c0d090e20f0cb56f70fcb56c54dd6582416974.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/1d448b059cddcc2f0705a4a4fe554e06261514.jpg",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/3c0d090e20f0cb56f70fcb56c54dd6582416974.png",
      "http://p1.meituan.net/pilotimages/1d448b059cddcc2f0705a4a4fe554e06261514.jpg"
    ],
    "color": "雾霾蓝",
    "design": "亮片",
    "styleLabel": "亮闪",
    "shapeLabel": "短圆",
    "styleTags": [
      "glitter"
    ],
    "materialTags": [
      "glitter"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1800,
    "rankWeight": 1.8,
    "isActive": true,
    "merchantId": null,
    "brief": "雾霾蓝·亮片·亮闪",
    "stylePrompt": "solid 雾霾蓝 color, 亮片 nail art pattern, 亮闪 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-6",
    "title": "纯黑·晕染",
    "coverUrl": "http://p0.meituan.net/pilotimages/6c857edd85a5fa4bcec59698fe9416cb1913981.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/a99d2de6bf0ade20211c0ae46af8e44b1057335.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/6c857edd85a5fa4bcec59698fe9416cb1913981.png",
      "http://p0.meituan.net/pilotimages/a99d2de6bf0ade20211c0ae46af8e44b1057335.png"
    ],
    "color": "纯黑",
    "design": "晕染",
    "styleLabel": "甜酷",
    "shapeLabel": "杏仁",
    "styleTags": [
      "cool"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "almond"
    ],
    "heat": 1760,
    "rankWeight": 1.76,
    "isActive": true,
    "merchantId": null,
    "brief": "纯黑·晕染·甜酷",
    "stylePrompt": "solid 纯黑 color, 晕染 nail art pattern, 甜酷 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-7",
    "title": "奶白·纯色",
    "coverUrl": "http://p0.meituan.net/pilotimages/2ac2d01a9bc78320edbe2b545b485b4a2132292.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/6dedbe1cfe7de834cd8faa4e19179fee1123627.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/2ac2d01a9bc78320edbe2b545b485b4a2132292.png",
      "http://p0.meituan.net/pilotimages/6dedbe1cfe7de834cd8faa4e19179fee1123627.png"
    ],
    "color": "奶白",
    "design": "纯色",
    "styleLabel": "复古",
    "shapeLabel": "方形",
    "styleTags": [
      "vintage"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "square"
    ],
    "heat": 1720,
    "rankWeight": 1.72,
    "isActive": true,
    "merchantId": null,
    "brief": "奶白·纯色·复古",
    "stylePrompt": "solid 奶白 color, 复古 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-8",
    "title": "焦糖棕·法式",
    "coverUrl": "http://p1.meituan.net/pilotimages/d15c06e8c2137d4f39f3b60476a90cf92026957.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/7b22fa4e6e1ee4e59a1115a27b125fe0996286.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/d15c06e8c2137d4f39f3b60476a90cf92026957.png",
      "http://p0.meituan.net/pilotimages/7b22fa4e6e1ee4e59a1115a27b125fe0996286.png"
    ],
    "color": "焦糖棕",
    "design": "法式",
    "styleLabel": "甜美",
    "shapeLabel": "圆形",
    "styleTags": [
      "fairy"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1680,
    "rankWeight": 1.6800000000000002,
    "isActive": true,
    "merchantId": null,
    "brief": "焦糖棕·法式·甜美",
    "stylePrompt": "solid 焦糖棕 color, 法式 nail art pattern, 甜美 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-9",
    "title": "裸透粉·渐变",
    "coverUrl": "http://p1.meituan.net/pilotimages/69614397f0ecb559b98cb46a5a46f3b32642714.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/6b20ca923ac4461aeaab7bf136bfda3c1063942.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/69614397f0ecb559b98cb46a5a46f3b32642714.png",
      "http://p0.meituan.net/pilotimages/6b20ca923ac4461aeaab7bf136bfda3c1063942.png"
    ],
    "color": "裸透粉",
    "design": "渐变",
    "styleLabel": "温柔",
    "shapeLabel": "梯形",
    "styleTags": [
      "gentle"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "trapezoid"
    ],
    "heat": 1640,
    "rankWeight": 1.6400000000000001,
    "isActive": true,
    "merchantId": null,
    "brief": "裸透粉·渐变·温柔",
    "stylePrompt": "solid 裸透粉 color, 渐变 nail art pattern, 温柔 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-10",
    "title": "奶茶色·猫眼",
    "coverUrl": "http://p1.meituan.net/pilotimages/2277d6f9d82264fa6a3c986373e5e44c2292083.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/a5894d122ca3bd7e1f12401a8c72351e1460094.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/2277d6f9d82264fa6a3c986373e5e44c2292083.png",
      "http://p0.meituan.net/pilotimages/a5894d122ca3bd7e1f12401a8c72351e1460094.png"
    ],
    "color": "奶茶色",
    "design": "猫眼",
    "styleLabel": "法式",
    "shapeLabel": "短圆",
    "styleTags": [
      "french"
    ],
    "materialTags": [
      "cat-eye"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1600,
    "rankWeight": 1.6,
    "isActive": true,
    "merchantId": null,
    "brief": "奶茶色·猫眼·法式",
    "stylePrompt": "solid 奶茶色 color, 猫眼 nail art pattern, 法式 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-11",
    "title": "酒红·亮片",
    "coverUrl": "http://p0.meituan.net/pilotimages/bc153edf655dd6961dc9f8e95ad8cd1e2561531.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/b6491d47c001ca175fa04e5243f84aa5896438.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/bc153edf655dd6961dc9f8e95ad8cd1e2561531.png",
      "http://p0.meituan.net/pilotimages/b6491d47c001ca175fa04e5243f84aa5896438.png"
    ],
    "color": "酒红",
    "design": "亮片",
    "styleLabel": "极简",
    "shapeLabel": "杏仁",
    "styleTags": [
      "minimal"
    ],
    "materialTags": [
      "glitter"
    ],
    "shapeTags": [
      "almond"
    ],
    "heat": 1560,
    "rankWeight": 1.56,
    "isActive": true,
    "merchantId": null,
    "brief": "酒红·亮片·极简",
    "stylePrompt": "solid 酒红 color, 亮片 nail art pattern, 极简 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-12",
    "title": "樱花粉·晕染",
    "coverUrl": "http://p0.meituan.net/pilotimages/43cc4ced977a3dd271f60ee2f05607772681747.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/d571f8a5702261542c115c247d210bfd1180529.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/43cc4ced977a3dd271f60ee2f05607772681747.png",
      "http://p1.meituan.net/pilotimages/d571f8a5702261542c115c247d210bfd1180529.png"
    ],
    "color": "樱花粉",
    "design": "晕染",
    "styleLabel": "奶油",
    "shapeLabel": "方形",
    "styleTags": [
      "cream"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "square"
    ],
    "heat": 1520,
    "rankWeight": 1.52,
    "isActive": true,
    "merchantId": null,
    "brief": "樱花粉·晕染·奶油",
    "stylePrompt": "solid 樱花粉 color, 晕染 nail art pattern, 奶油 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-13",
    "title": "雾霾蓝·纯色",
    "coverUrl": "http://p0.meituan.net/pilotimages/682c173ae3a95d0b838655e8337b30d72213857.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/5fa531643ac8f829d8ab574b4c11e0081087649.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/682c173ae3a95d0b838655e8337b30d72213857.png",
      "http://p0.meituan.net/pilotimages/5fa531643ac8f829d8ab574b4c11e0081087649.png"
    ],
    "color": "雾霾蓝",
    "design": "纯色",
    "styleLabel": "亮闪",
    "shapeLabel": "圆形",
    "styleTags": [
      "glitter"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1480,
    "rankWeight": 1.48,
    "isActive": true,
    "merchantId": null,
    "brief": "雾霾蓝·纯色·亮闪",
    "stylePrompt": "solid 雾霾蓝 color, 亮闪 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-14",
    "title": "纯黑·法式",
    "coverUrl": "http://p1.meituan.net/pilotimages/eecfba4ab276e895b579a79491b2d0211982788.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/b99490b3f4a5e088ffe36c6ae60211941005960.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/eecfba4ab276e895b579a79491b2d0211982788.png",
      "http://p0.meituan.net/pilotimages/b99490b3f4a5e088ffe36c6ae60211941005960.png"
    ],
    "color": "纯黑",
    "design": "法式",
    "styleLabel": "甜酷",
    "shapeLabel": "梯形",
    "styleTags": [
      "cool"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "trapezoid"
    ],
    "heat": 1440,
    "rankWeight": 1.44,
    "isActive": true,
    "merchantId": null,
    "brief": "纯黑·法式·甜酷",
    "stylePrompt": "solid 纯黑 color, 法式 nail art pattern, 甜酷 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-15",
    "title": "奶白·渐变",
    "coverUrl": "http://p0.meituan.net/pilotimages/1248ad42d355b98257e5fbcdf90efc552138079.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/5c66d21b6fc2b78c59f3f2e36fc788451052442.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/1248ad42d355b98257e5fbcdf90efc552138079.png",
      "http://p0.meituan.net/pilotimages/5c66d21b6fc2b78c59f3f2e36fc788451052442.png"
    ],
    "color": "奶白",
    "design": "渐变",
    "styleLabel": "复古",
    "shapeLabel": "短圆",
    "styleTags": [
      "vintage"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1400,
    "rankWeight": 1.4,
    "isActive": true,
    "merchantId": null,
    "brief": "奶白·渐变·复古",
    "stylePrompt": "solid 奶白 color, 渐变 nail art pattern, 复古 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-16",
    "title": "焦糖棕·猫眼",
    "coverUrl": "http://p0.meituan.net/pilotimages/137aad1f6a36655ae395cf7dc57604642782680.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/81a8b3a96d3dd6ba1c849cc666bf85f51089012.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/137aad1f6a36655ae395cf7dc57604642782680.png",
      "http://p0.meituan.net/pilotimages/81a8b3a96d3dd6ba1c849cc666bf85f51089012.png"
    ],
    "color": "焦糖棕",
    "design": "猫眼",
    "styleLabel": "甜美",
    "shapeLabel": "杏仁",
    "styleTags": [
      "fairy"
    ],
    "materialTags": [
      "cat-eye"
    ],
    "shapeTags": [
      "almond"
    ],
    "heat": 1360,
    "rankWeight": 1.3599999999999999,
    "isActive": true,
    "merchantId": null,
    "brief": "焦糖棕·猫眼·甜美",
    "stylePrompt": "solid 焦糖棕 color, 猫眼 nail art pattern, 甜美 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-17",
    "title": "裸透粉·亮片",
    "coverUrl": "http://p0.meituan.net/pilotimages/ec437f6291295904c2f894edb8c01cb82131722.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/ff68ba22d655fd1e0a812f197e406d951137747.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/ec437f6291295904c2f894edb8c01cb82131722.png",
      "http://p0.meituan.net/pilotimages/ff68ba22d655fd1e0a812f197e406d951137747.png"
    ],
    "color": "裸透粉",
    "design": "亮片",
    "styleLabel": "温柔",
    "shapeLabel": "方形",
    "styleTags": [
      "gentle"
    ],
    "materialTags": [
      "glitter"
    ],
    "shapeTags": [
      "square"
    ],
    "heat": 1320,
    "rankWeight": 1.32,
    "isActive": true,
    "merchantId": null,
    "brief": "裸透粉·亮片·温柔",
    "stylePrompt": "solid 裸透粉 color, 亮片 nail art pattern, 温柔 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-18",
    "title": "奶茶色·晕染",
    "coverUrl": "http://p0.meituan.net/pilotimages/5591229138c4e7e1d183b59be442d9dc2267735.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/29c85d420f45062d29890f4ae014b82f960529.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/5591229138c4e7e1d183b59be442d9dc2267735.png",
      "http://p1.meituan.net/pilotimages/29c85d420f45062d29890f4ae014b82f960529.png"
    ],
    "color": "奶茶色",
    "design": "晕染",
    "styleLabel": "法式",
    "shapeLabel": "圆形",
    "styleTags": [
      "french"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1280,
    "rankWeight": 1.28,
    "isActive": true,
    "merchantId": null,
    "brief": "奶茶色·晕染·法式",
    "stylePrompt": "solid 奶茶色 color, 晕染 nail art pattern, 法式 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-19",
    "title": "酒红·纯色",
    "coverUrl": "http://p0.meituan.net/pilotimages/5fad21e6d38656170bf726ff3973a4501918338.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/b6a8da8cb0d46f30ec2c65b79c3710e91040053.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/5fad21e6d38656170bf726ff3973a4501918338.png",
      "http://p0.meituan.net/pilotimages/b6a8da8cb0d46f30ec2c65b79c3710e91040053.png"
    ],
    "color": "酒红",
    "design": "纯色",
    "styleLabel": "极简",
    "shapeLabel": "梯形",
    "styleTags": [
      "minimal"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "trapezoid"
    ],
    "heat": 1240,
    "rankWeight": 1.24,
    "isActive": true,
    "merchantId": null,
    "brief": "酒红·纯色·极简",
    "stylePrompt": "solid 酒红 color, 极简 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-20",
    "title": "樱花粉·法式",
    "coverUrl": "http://p1.meituan.net/pilotimages/d5eedc75b0021f79381962fc145b0bc62301165.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/7f3d1832f40e03685a0e413e6196efcd1139460.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/d5eedc75b0021f79381962fc145b0bc62301165.png",
      "http://p0.meituan.net/pilotimages/7f3d1832f40e03685a0e413e6196efcd1139460.png"
    ],
    "color": "樱花粉",
    "design": "法式",
    "styleLabel": "奶油",
    "shapeLabel": "短圆",
    "styleTags": [
      "cream"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1200,
    "rankWeight": 1.2,
    "isActive": true,
    "merchantId": null,
    "brief": "樱花粉·法式·奶油",
    "stylePrompt": "solid 樱花粉 color, 法式 nail art pattern, 奶油 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-21",
    "title": "雾霾蓝·渐变",
    "coverUrl": "http://p0.meituan.net/pilotimages/f4b69d45af5d3b496adbd9d21e768a8e2195181.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/fe1824a01b10a0fee24a8aaa5b1ef1991009918.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/f4b69d45af5d3b496adbd9d21e768a8e2195181.png",
      "http://p0.meituan.net/pilotimages/fe1824a01b10a0fee24a8aaa5b1ef1991009918.png"
    ],
    "color": "雾霾蓝",
    "design": "渐变",
    "styleLabel": "亮闪",
    "shapeLabel": "杏仁",
    "styleTags": [
      "glitter"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "almond"
    ],
    "heat": 1160,
    "rankWeight": 1.16,
    "isActive": true,
    "merchantId": null,
    "brief": "雾霾蓝·渐变·亮闪",
    "stylePrompt": "solid 雾霾蓝 color, 渐变 nail art pattern, 亮闪 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-22",
    "title": "纯黑·猫眼",
    "coverUrl": "http://p0.meituan.net/pilotimages/5b985a1c661ae2e964286178e6c0b0f92258113.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/1e86c987caf89d5b15a226ad097e270b963164.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/5b985a1c661ae2e964286178e6c0b0f92258113.png",
      "http://p0.meituan.net/pilotimages/1e86c987caf89d5b15a226ad097e270b963164.png"
    ],
    "color": "纯黑",
    "design": "猫眼",
    "styleLabel": "甜酷",
    "shapeLabel": "方形",
    "styleTags": [
      "cool"
    ],
    "materialTags": [
      "cat-eye"
    ],
    "shapeTags": [
      "square"
    ],
    "heat": 1120,
    "rankWeight": 1.12,
    "isActive": true,
    "merchantId": null,
    "brief": "纯黑·猫眼·甜酷",
    "stylePrompt": "solid 纯黑 color, 猫眼 nail art pattern, 甜酷 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-23",
    "title": "奶白·亮片",
    "coverUrl": "http://p1.meituan.net/pilotimages/bf8657d94693fb0fe1da3f7729d5667d2020119.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/ec8057452f9520a0ca5cdba3f78f6f80982638.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/bf8657d94693fb0fe1da3f7729d5667d2020119.png",
      "http://p0.meituan.net/pilotimages/ec8057452f9520a0ca5cdba3f78f6f80982638.png"
    ],
    "color": "奶白",
    "design": "亮片",
    "styleLabel": "复古",
    "shapeLabel": "圆形",
    "styleTags": [
      "vintage"
    ],
    "materialTags": [
      "glitter"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1080,
    "rankWeight": 1.08,
    "isActive": true,
    "merchantId": null,
    "brief": "奶白·亮片·复古",
    "stylePrompt": "solid 奶白 color, 亮片 nail art pattern, 复古 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-24",
    "title": "焦糖棕·晕染",
    "coverUrl": "http://p0.meituan.net/pilotimages/e80e1d25e48d7ef5c505b29ee8e331822641412.png",
    "sourceUrl": "http://p1.meituan.net/pilotimages/1fb5e1b20aea0b0881a4eb5d41bff80b1076304.png",
    "previewUrls": [
      "http://p0.meituan.net/pilotimages/e80e1d25e48d7ef5c505b29ee8e331822641412.png",
      "http://p1.meituan.net/pilotimages/1fb5e1b20aea0b0881a4eb5d41bff80b1076304.png"
    ],
    "color": "焦糖棕",
    "design": "晕染",
    "styleLabel": "甜美",
    "shapeLabel": "梯形",
    "styleTags": [
      "fairy"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "trapezoid"
    ],
    "heat": 1040,
    "rankWeight": 1.04,
    "isActive": true,
    "merchantId": null,
    "brief": "焦糖棕·晕染·甜美",
    "stylePrompt": "solid 焦糖棕 color, 晕染 nail art pattern, 甜美 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  },
  {
    "id": "real-25",
    "title": "裸透粉·纯色",
    "coverUrl": "http://p1.meituan.net/pilotimages/73ee568aa09547d8bfc0168113ac9ebc2712329.png",
    "sourceUrl": "http://p0.meituan.net/pilotimages/0d9545bd4583f87e8cc3882d15ff84101211916.png",
    "previewUrls": [
      "http://p1.meituan.net/pilotimages/73ee568aa09547d8bfc0168113ac9ebc2712329.png",
      "http://p0.meituan.net/pilotimages/0d9545bd4583f87e8cc3882d15ff84101211916.png"
    ],
    "color": "裸透粉",
    "design": "纯色",
    "styleLabel": "温柔",
    "shapeLabel": "短圆",
    "styleTags": [
      "gentle"
    ],
    "materialTags": [
      "jelly"
    ],
    "shapeTags": [
      "round"
    ],
    "heat": 1000,
    "rankWeight": 1,
    "isActive": true,
    "merchantId": null,
    "brief": "裸透粉·纯色·温柔",
    "stylePrompt": "solid 裸透粉 color, 温柔 style, gel nail polish, natural finish",
    "createdAt": "2026-05-24"
  }
];
