#!/usr/bin/env node
/**
 * 从 data/*.xlsx 导入真实款式 → nailmirror/src/mock/styles.real.js
 * 用法：
 *   node scripts/import-styles.js              # 无 VLM，用默认标签
 *   DASHSCOPE_API_KEY=sk-xxx node scripts/import-styles.js --vlm  # Qwen-VL 打标
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const DATA_DIR = path.join(ROOT, 'data');
const OUT = path.join(ROOT, 'nailmirror', 'src', 'mock', 'styles.real.js');

const DEFAULT_STYLES = ['gentle', 'french', 'minimal', 'cream', 'glitter', 'cool', 'vintage', 'fairy'];
const DEFAULT_COLORS = ['裸透粉', '奶茶色', '酒红', '樱花粉', '雾霾蓝', '纯黑', '奶白', '焦糖棕'];
const DEFAULT_DESIGNS = ['纯色', '法式', '渐变', '猫眼', '亮片', '晕染'];
const DEFAULT_SHAPES = ['杏仁', '方形', '圆形', '梯形', '短圆'];

/** 小程序真机要求 HTTPS，Excel 中可能是 http:// */
function toHttpsUrl(url) {
  if (!url || typeof url !== 'string') return url;
  return url.replace(/^http:\/\//i, 'https://');
}

function loadXlsxRows() {
  const { execSync } = require('child_process');
  const pyScript = path.join(__dirname, 'read_styles_xlsx.py');
  const raw = execSync(`python "${pyScript}" "${DATA_DIR}"`, { encoding: 'utf8' });
  return JSON.parse(raw.trim());
}

async function tagWithVlm(imageUrl, apiKey) {
  const axios = require('axios');
  const prompt = [
    '你是美甲款式识别器。分析图片，只输出 JSON，禁止任何解释。',
    'schema: {"color":"...","design":"...","shape":"...","style":"...","name":"..."}',
    'color=颜色标签, design=图案(纯色/法式/猫眼等), shape=甲型, style=风格, name=10字内展示名'
  ].join('\n');

  const res = await axios.post(
    'https://dashscope.aliyuncs.com/compatible-mode/v1/chat/completions',
    {
      model: process.env.QWEN_VL_MODEL || 'qwen-vl-max',
      messages: [{
        role: 'user',
        content: [
          { type: 'image_url', image_url: { url: imageUrl } },
          { type: 'text', text: prompt }
        ]
      }]
    },
    { headers: { Authorization: 'Bearer ' + apiKey }, timeout: 60000 }
  );

  const text = res.data.choices[0].message.content || '';
  const m = text.match(/\{[\s\S]*\}/);
  if (!m) throw new Error('VLM 未返回 JSON: ' + text.slice(0, 200));
  return JSON.parse(m[0]);
}

function defaultTags(idx) {
  const i = idx - 1;
  const styleId = DEFAULT_STYLES[i % DEFAULT_STYLES.length];
  const styleLabels = { gentle: '温柔', french: '法式', minimal: '极简', cream: '奶油', glitter: '亮闪', cool: '甜酷', vintage: '复古', fairy: '甜美' };
  const color = DEFAULT_COLORS[i % DEFAULT_COLORS.length];
  const design = DEFAULT_DESIGNS[i % DEFAULT_DESIGNS.length];
  const shape = DEFAULT_SHAPES[i % DEFAULT_SHAPES.length];
  return {
    color, design, shape,
    style: styleLabels[styleId] || '温柔',
    name: color + '·' + design
  };
}

function toNailStyle(row, tags) {
  const { mapStyleCn, mapShapeCn, inferMaterialTags, STYLE_ID_TO_LABEL, SHAPE_ID_TO_LABEL } = require('../nailmirror/src/config/label-maps');
  const styleTag = mapStyleCn(tags.style);
  const shapeTag = mapShapeCn(tags.shape);
  const styleLabel = tags.style || STYLE_ID_TO_LABEL[styleTag];
  const shapeLabel = tags.shape || SHAPE_ID_TO_LABEL[shapeTag];
  const title = tags.name || (tags.color + '·' + tags.design);
  const idx = row.idx;

  const enhanced = toHttpsUrl(row.enhanced);
  const orig = toHttpsUrl(row.orig);

  return {
    id: 'real-' + idx,
    title,
    coverUrl: enhanced,
    sourceUrl: orig,
    previewUrls: [enhanced, orig].filter(Boolean),
    color: tags.color,
    design: tags.design,
    styleLabel,
    shapeLabel,
    styleTags: [styleTag],
    materialTags: inferMaterialTags(tags.color, tags.design),
    shapeTags: [shapeTag],
    heat: Math.round((1 + (25 - idx) * 0.04) * 1000),
    rankWeight: 1 + (25 - idx) * 0.04,
    isActive: true,
    merchantId: null,
    brief: [tags.color, tags.design, styleLabel].filter(Boolean).join('·'),
    stylePrompt: require('../nailmirror/src/config/label-maps').buildStylePrompt(tags.color, tags.design, styleLabel),
    createdAt: '2026-05-24'
  };
}

async function main() {
  const useVlm = process.argv.includes('--vlm');
  const apiKey = process.env.DASHSCOPE_API_KEY || '';
  if (useVlm && !apiKey) {
    console.error('需要环境变量 DASHSCOPE_API_KEY');
    process.exit(1);
  }

  const rows = loadXlsxRows();
  console.log('读取', rows.length, '条款式');

  const items = [];
  for (const row of rows) {
    let tags;
    if (useVlm) {
      try {
        tags = await tagWithVlm(toHttpsUrl(row.enhanced), apiKey);
        console.log('VLM', row.idx, tags.name || tags.color);
        await new Promise((r) => setTimeout(r, 500));
      } catch (e) {
        console.warn('VLM 失败', row.idx, e.message, '→ 默认标签');
        tags = defaultTags(row.idx);
      }
    } else {
      tags = defaultTags(row.idx);
    }
    items.push(toNailStyle(row, tags));
  }

  const content = '// AUTO-GENERATED by scripts/import-styles.js — DO NOT EDIT BY HAND\nmodule.exports = ' + JSON.stringify(items, null, 2) + ';\n';
  fs.writeFileSync(OUT, content, 'utf8');
  console.log('已写入', OUT, '(', items.length, '条)');
}

main().catch((e) => { console.error(e); process.exit(1); });
